In [4]:
%matplotlib inline

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Tidying and Cleaning #

In [5]:
pew = pd.read_csv("Lab/pew.csv")

In [6]:
pew

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Donâ€™t know/refused,15,14,15,11,10,35,21,17,18,116
5,Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
6,Hindu,1,9,7,9,11,34,47,48,54,37
7,Historically Black Prot,228,244,236,238,197,223,131,81,78,339
8,Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
9,Jewish,19,19,25,25,30,95,69,87,151,162
10,Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
11,Mormon,29,40,48,51,56,112,85,49,42,69
12,Muslim,6,7,9,10,9,23,16,8,6,22
13,Orthodox,13,17,23,32,32,47,38,42,46,73
14,Other Christian,9,7,11,13,13,14,18,14,12,18
15,Other Faiths,20,33,40,46,49,63,46,40,41,71
16,Other World Religions,5,2,3,4,2,7,3,4,4,8
17,Unaffiliated,217,299,374,365,341,528,407,321,258,597

In [11]:
pew_tidy = pew.melt(id_vars=["religion"], var_name = "income", value_name = "frequency")

In [12]:
pew_tidy

                  religion              income  frequency
0                 Agnostic               <$10k         27
1                  Atheist               <$10k         12
2                 Buddhist               <$10k         27
3                 Catholic               <$10k        418
4       Donâ€™t know/refused               <$10k         15
..                     ...                 ...        ...
175               Orthodox  Don't know/refused         73
176        Other Christian  Don't know/refused         18
177           Other Faiths  Don't know/refused         71
178  Other World Religions  Don't know/refused          8
179           Unaffiliated  Don't know/refused        597

[180 rows x 3 columns]

In [23]:
pew_tidy.religion = pew_tidy.religion.astype("category")

In [25]:
pew_tidy.income = pew_tidy.income.astype("category")

In [26]:
pew_tidy.dtypes

religion     category
income       category
frequency       int64
dtype: object